### ISSUE TITLE
Register: Create toast for password requirements

### ISSUE THREAD

**Issue by ezhao7** [GT-Hive/hive#13] opened 2019-02-08 18:36 UTC
Only show a popup toast when tapped on the password input for the requirements.

**Comment by sroyhong313** [comment] 2019-02-10 20:59
this seems like a duplicate of #1. I'll close it for now

**Closed by sroyhong313** 2019-02-10 20:59 UTC
Labels: Duplicate, Ready for: Design, enhancement

**Comment by ezhao7** [comment] 2019-02-10 21:01
It's a bit more specific than just a broad scoped #1, but my bad on not being understanding on the scope.
